# Sample workflow for building and deploying an Astro site to GitHub Pages
#
# To get started with Astro see: https://docs.astro.build/en/getting-started/
#
name: Build Astro.js static site package and deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build with Astro
        run: yarn build
      - name: Generate build artifact
        run: cd dist && tar -cvzf ../sector-umbra.net-dist.tar.gz ./
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: sector-umbra.net-dist.tar.gz
          path: sector-umbra.net-dist.tar.g
          if-no-files-found: error
          retention-days: 1
          overwrite: true
  # To do: deploy job
